[package]
name = "attic-client"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "attic"
path = "src/main.rs"

[dependencies]
attic = { path = "../attic" }

anyhow = { workspace = true }
async-channel = "2.5.0"
bytes = { workspace = true }
clap = { workspace = true }
clap_complete = "4.5.54"
const_format = "0.2.34"
dialoguer = "0.12.0"
displaydoc = { workspace = true }
enum-as-inner = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
indicatif = "0.18.0"
lazy_static = { workspace = true }
notify = { version = "8.1.0", default-features = false, features = ["macos_kqueue"] }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
xdg = { workspace = true }

[dependencies.tokio]
version = "1.46.1"
features = [
	"fs",
	"io-std",
	"io-util",
	"macros",
	"process",
	"rt",
	"rt-multi-thread",
	"sync",
]
