[package]
name = "attic-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
attic = { path = "../attic", default-features = false }

base64 = { workspace = true }
chrono = { workspace = true }
displaydoc = { workspace = true }
indexmap = { version = "2.10.0", features = ["serde"] }
jwt-simple = "0.12"
lazy_static = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
tracing = { workspace = true }
rsa = { workspace = true }
