[package]
name = "attic-server"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "attic_server"
path = "src/lib.rs"

[[bin]]
name = "atticd"
path = "src/main.rs"
doc = false

[[bin]]
name = "atticadm"
path = "src/adm/main.rs"
doc = false

[dependencies]
attic = { path = "../attic", default-features = false, features = ["chunking", "io", "tokio"] }
attic-token = { path = "../token" }

anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
aws-config = "1.8.1"
axum = "0.7.9"
axum-macros = "0.4.2"
aws-sdk-s3 = "1.127"
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
displaydoc = { workspace = true }
enum-as-inner = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http-body-util = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
itoa = "1.0.15"
rand = { workspace = true }
regex = { workspace = true }
ryu = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
tower-http = { version = "0.5.2", features = [ "catch-panic", "trace" ] }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
console-subscriber = "0.5"
xdg = { workspace = true }
rsa = { workspace = true }

[dependencies.async-compression]
workspace = true

[dependencies.sea-orm]
workspace = true
features = [
	"runtime-tokio-rustls",
	"macros",
	"sqlx-postgres",
	"sqlx-sqlite",
	"debug-print",
]

[dependencies.sea-orm-migration]
version = "1.1.13"

[dependencies.tokio]
workspace = true
features = [
	"fs",
	"io-util",
	"macros",
	"process",
	"rt",
	"rt-multi-thread",
	"sync",
]
